// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// THE POLAR COAST'S BIRDS — the arctic third of the roster, beside
// `bird-defs.ts` for the reason `flora-defs-arctic.ts` is beside the cover:
// one subject, one planner, one lab, and a parent file past the §20.5 cap.
// `BIRDS` is still how the whole app spells the roster — `bird-defs.ts`
// spreads these rows onto the end of it — and nothing anywhere reads this
// module directly. What a row MEANS is stated there; which of the birds a
// polar coast has and why is in that file's header with the other coasts'.

import type { BirdSpec } from "./bird-defs.ts";

export const ARCTIC_BIRDS: readonly BirdSpec[] = [
  {
    id: "glaucous",
    name: "Glaucous gull",
    biomes: ["arctic"],
    // The polar coast's gull: bigger than the herring gull, paler, and
    // with NO black in the wingtip at all — a big white gull is a glaucous
    // gull, from any distance.
    span: 1.6,
    length: 0.7,
    neck: 0.38,
    wing: { chord: 0.16, taper: 0.4, sweep: 0.2, wrist: 0.42 },
    beatHz: 2.8,
    stroke: 0.75,
    glide: 0.5,
    dihedral: 0.05,
    speed: 12,
    flock: { min: 2, max: 9 },
    formation: "loose",
    altitude: { min: 10, max: 45 },
    beat: { min: 30, max: 90 },
    home: "skerry",
    roost: 6,
    cycle: { min: 70, max: 150 },
    airShare: 0.55,
    dive: 0,
    dries: false,
    // The everyday bird of the coast, as the herring gull is of the taiga.
    perKm: 1.6,
    seasons: ["spring", "summer", "autumn", "winter"],
    passes: [],
  },
  {
    id: "ivorygull",
    name: "Ivory gull",
    biomes: ["arctic"],
    // WHITE TO THE TIPS, with black legs: the ice's own gull, and the one
    // bird that lives out on the pack all winter, following the bears for
    // what they leave. Smaller and quicker than any other gull here.
    span: 1.12,
    length: 0.42,
    neck: 0.37,
    wing: { chord: 0.15, taper: 0.36, sweep: 0.24, wrist: 0.42 },
    beatHz: 3.6,
    stroke: 0.85,
    glide: 0.35,
    dihedral: 0.04,
    speed: 13,
    flock: { min: 2, max: 6 },
    formation: "loose",
    altitude: { min: 6, max: 30 },
    beat: { min: 30, max: 90 },
    // On the ice: a berg, a floe, whatever stands out of the water.
    home: "skerry",
    roost: 5,
    cycle: { min: 80, max: 160 },
    airShare: 0.5,
    dive: 0,
    dries: false,
    perKm: 0.6,
    seasons: ["spring", "summer", "autumn", "winter"],
    passes: [],
  },
  {
    id: "littleauk",
    name: "Little auk",
    biomes: ["arctic"],
    // THE SMALLEST SEABIRD IN THE ROSTER and the most numerous bird in
    // the polar sea: a starling-sized black-and-white auk in flocks of
    // dozens, whirring low over the water on the fastest wingbeat here
    // and never gliding at all. A flock of them is the open water's own.
    span: 0.36,
    length: 0.2,
    neck: 0.36,
    // Short and narrow: an auk's wing is a flipper that flies.
    wing: { chord: 0.16, taper: 0.5, sweep: 0.1, wrist: 0.5 },
    beatHz: 9,
    stroke: 0.65,
    glide: 0,
    dihedral: 0,
    speed: 15,
    flock: { min: 12, max: 30 },
    formation: "loose",
    altitude: { min: 1.5, max: 6 },
    beat: { min: 50, max: 140 },
    home: "water",
    roost: 10,
    cycle: { min: 90, max: 200 },
    airShare: 0.45,
    dive: 0,
    dries: false,
    perKm: 1.2,
    // Out over the water with depth under it, and off the line: a raft of
    // little auks is met by riding out.
    sea: { offshore: { min: 110, max: 800 }, reach: 900 },
    seasons: ["spring", "summer"],
    passes: [],
  },
  {
    id: "guillemot",
    name: "Thick-billed murre",
    biomes: ["arctic"],
    // The bird-cliff bird: a black-and-white auk the size of a duck, in
    // lines low and fast over the water between the cliff and the sea,
    // beating without a pause.
    span: 0.72,
    length: 0.42,
    neck: 0.4,
    wing: { chord: 0.16, taper: 0.5, sweep: 0.1, wrist: 0.5 },
    beatHz: 7.5,
    stroke: 0.6,
    glide: 0,
    dihedral: 0,
    speed: 17,
    flock: { min: 4, max: 12 },
    formation: "line",
    altitude: { min: 2, max: 8 },
    beat: { min: 60, max: 150 },
    // The ledges: a berg, a stack, the wall's foot — any rock standing
    // out of the water is a ledge to a murre.
    home: "skerry",
    roost: 5,
    cycle: { min: 120, max: 240 },
    airShare: 0.3,
    dive: 0,
    dries: false,
    perKm: 0.9,
    seasons: ["spring", "summer", "autumn"],
    passes: [],
  },
  {
    id: "puffin",
    name: "Puffin",
    biomes: ["arctic"],
    span: 0.55,
    length: 0.3,
    neck: 0.4,
    wing: { chord: 0.17, taper: 0.5, sweep: 0.1, wrist: 0.5 },
    beatHz: 7,
    stroke: 0.6,
    glide: 0,
    dihedral: 0,
    speed: 15,
    flock: { min: 3, max: 8 },
    formation: "loose",
    altitude: { min: 2, max: 10 },
    beat: { min: 50, max: 130 },
    home: "skerry",
    roost: 4,
    cycle: { min: 120, max: 240 },
    airShare: 0.3,
    dive: 0,
    dries: false,
    perKm: 0.5,
    seasons: ["spring", "summer"],
    passes: [],
  },
  {
    id: "blackguillemot",
    name: "Black guillemot",
    biomes: ["arctic"],
    // Black with a WHITE WING PATCH and red feet, in twos and threes
    // along the scree at the foot of the wall — the one auk that stays
    // inshore, and the one that winters at the ice edge.
    span: 0.55,
    length: 0.31,
    neck: 0.38,
    wing: { chord: 0.17, taper: 0.5, sweep: 0.1, wrist: 0.5 },
    beatHz: 7,
    stroke: 0.6,
    glide: 0,
    dihedral: 0,
    speed: 14,
    flock: { min: 2, max: 5 },
    formation: "loose",
    altitude: { min: 1.5, max: 6 },
    beat: { min: 40, max: 110 },
    home: "skerry",
    roost: 4,
    cycle: { min: 120, max: 240 },
    airShare: 0.3,
    dive: 0,
    dries: false,
    perKm: 0.7,
    seasons: ["spring", "summer", "autumn", "winter"],
    passes: [],
  },
  {
    id: "kingeider",
    name: "King eider",
    biomes: ["arctic"],
    // The eider of the polar sea: the drake's orange shield on a black
    // duck, rafting in the lee of a floe, and up off the water in a line
    // when the craft comes. A duck's wing, beating the whole way.
    span: 0.95,
    length: 0.55,
    neck: 0.34,
    wing: { chord: 0.17, taper: 0.5, sweep: 0.1, wrist: 0.52 },
    beatHz: 5.5,
    stroke: 0.6,
    glide: 0,
    dihedral: 0,
    speed: 18,
    flock: { min: 6, max: 16 },
    formation: "line",
    altitude: { min: 1.5, max: 5 },
    beat: { min: 60, max: 150 },
    home: "water",
    roost: 9,
    cycle: { min: 150, max: 320 },
    airShare: 0.14,
    dive: 0,
    dries: false,
    perKm: 0.7,
    seasons: ["spring", "summer", "autumn"],
    passes: [],
  },
  {
    id: "longtail",
    name: "Long-tailed duck",
    biomes: ["arctic"],
    // A small quick sea duck in a raft off the gravel, and the noisiest
    // duck on any coast.
    span: 0.72,
    length: 0.45,
    neck: 0.36,
    wing: { chord: 0.17, taper: 0.5, sweep: 0.1, wrist: 0.52 },
    beatHz: 6,
    stroke: 0.6,
    glide: 0,
    dihedral: 0,
    speed: 18,
    flock: { min: 5, max: 14 },
    formation: "line",
    altitude: { min: 1.5, max: 5 },
    beat: { min: 50, max: 130 },
    home: "water",
    roost: 8,
    cycle: { min: 150, max: 320 },
    airShare: 0.16,
    dive: 0,
    dries: false,
    perKm: 0.6,
    seasons: ["spring", "summer", "autumn"],
    passes: [],
  },
  {
    id: "brent",
    name: "Brent goose",
    biomes: ["arctic"],
    // A small dark goose: on the water off the islets through the summer,
    // and in the spring and the autumn a skein going over — south ahead
    // of the ice, north behind it.
    span: 1.15,
    length: 0.6,
    neck: 0.38,
    wing: { chord: 0.17, taper: 0.4, sweep: 0.14, wrist: 0.48 },
    beatHz: 3.4,
    stroke: 0.85,
    glide: 0.1,
    dihedral: 0.06,
    speed: 19,
    flock: { min: 3, max: 8 },
    formation: "line",
    altitude: { min: 15, max: 50 },
    beat: { min: 80, max: 180 },
    home: "water",
    roost: 8,
    cycle: { min: 160, max: 300 },
    airShare: 0.22,
    dive: 0,
    dries: false,
    perKm: 0.3,
    seasons: ["summer"],
    passage: {
      height: { min: 80, max: 140 },
      birds: { min: 8, max: 20 },
      shapes: ["vee", "line"],
      share: 4,
    },
    passes: ["spring", "autumn"],
  },
  {
    id: "snowgoose",
    name: "Snow goose",
    biomes: ["arctic"],
    // WHITE WITH BLACK WINGTIPS, in a vee at height — and never on this
    // shore: the snow goose is a thing that goes over, the crane's part on
    // a coast with no cranes.
    span: 1.5,
    length: 0.75,
    neck: 0.4,
    wing: { chord: 0.17, taper: 0.42, sweep: 0.14, wrist: 0.48 },
    beatHz: 3,
    stroke: 0.8,
    glide: 0.12,
    dihedral: 0.06,
    speed: 18,
    flock: { min: 8, max: 18 },
    formation: "vee",
    altitude: { min: 60, max: 140 },
    beat: { min: 100, max: 200 },
    roost: 0,
    cycle: { min: 200, max: 400 },
    airShare: 0,
    dive: 0,
    dries: false,
    perKm: 0,
    seasons: [],
    passage: {
      height: { min: 100, max: 170 },
      birds: { min: 8, max: 18 },
      shapes: ["vee"],
      share: 3,
    },
    passes: ["spring", "autumn"],
  },
  {
    id: "skua",
    name: "Arctic skua",
    biomes: ["arctic"],
    // A dark, falcon-winged gull that lives by robbing the terns: one or
    // two over the tern colony on the gravel, fast and low, and off after
    // anything carrying a fish.
    span: 1.15,
    length: 0.44,
    neck: 0.38,
    wing: { chord: 0.13, taper: 0.3, sweep: 0.3, wrist: 0.4 },
    beatHz: 3.4,
    stroke: 0.8,
    glide: 0.5,
    dihedral: 0.03,
    speed: 14,
    flock: { min: 1, max: 2 },
    formation: "loose",
    altitude: { min: 6, max: 30 },
    beat: { min: 40, max: 110 },
    home: "shore",
    roost: 6,
    cycle: { min: 90, max: 200 },
    airShare: 0.6,
    dive: 0,
    dries: false,
    perKm: 0.5,
    seasons: ["spring", "summer"],
    passes: [],
  },
  {
    id: "gyrfalcon",
    name: "Gyrfalcon",
    biomes: ["arctic"],
    // THE POLAR COAST'S RAPTOR: the biggest falcon there is, grey or white,
    // one to a cliff — and here the cliff is whatever stands out of the
    // water, because there is no tree on this coast for anything to sit
    // in. It flies high and fast on a broad falcon's wing, and glides
    // more than it beats.
    span: 1.25,
    length: 0.55,
    neck: 0.36,
    wing: { chord: 0.2, taper: 0.4, sweep: 0.26, wrist: 0.45 },
    beatHz: 2.6,
    stroke: 0.6,
    glide: 0.65,
    dihedral: 0.04,
    speed: 16,
    flock: { min: 1, max: 1 },
    formation: "loose",
    altitude: { min: 40, max: 110 },
    beat: { min: 70, max: 160 },
    home: "skerry",
    roost: 0,
    cycle: { min: 180, max: 320 },
    airShare: 0.55,
    dive: 0,
    dries: false,
    perKm: 0.25,
    seasons: ["spring", "summer", "autumn", "winter"],
    passes: [],
  },
  {
    id: "raven",
    name: "Raven",
    biomes: ["arctic"],
    // Black, big, and here the whole year — the one land bird a polar
    // coast keeps through the dark: a pair along the wall's foot, tumbling
    // in the updraught off it.
    span: 1.3,
    length: 0.63,
    neck: 0.4,
    wing: { chord: 0.2, taper: 0.5, sweep: 0.14, wrist: 0.48 },
    beatHz: 2.8,
    stroke: 0.7,
    glide: 0.45,
    dihedral: 0.04,
    speed: 13,
    flock: { min: 1, max: 2 },
    formation: "loose",
    altitude: { min: 15, max: 60 },
    beat: { min: 50, max: 130 },
    home: "shore",
    roost: 4,
    cycle: { min: 150, max: 300 },
    airShare: 0.5,
    dive: 0,
    dries: false,
    perKm: 0.35,
    seasons: ["spring", "summer", "autumn", "winter"],
    passes: [],
  },
];
