// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// THE KARST COAST'S BIRDS — the fourth quarter of the roster, beside
// `bird-defs.ts` for the reason `bird-defs-arctic.ts` is: one subject, one
// planner, one lab, and a parent file past the §20.5 cap. `BIRDS` is still
// how the whole app spells the roster — `bird-defs.ts` spreads these rows
// onto the end of it — and nothing anywhere reads this module directly.
// What a row MEANS is stated there; which of the birds a limestone coast
// has and why is in that file's header with the other coasts'.

import type { BirdSpec } from "./bird-defs.ts";

export const KARST_BIRDS: readonly BirdSpec[] = [
  {
    id: "yellowlegged",
    name: "Yellow-legged gull",
    biomes: ["karst"],
    // The everyday bird of this coast, and it is a LOUD one: the herring
    // gull's southern cousin, a shade darker on the mantle, on every
    // islet and every harbour wall and over every boat.
    span: 1.45,
    length: 0.6,
    neck: 0.38,
    wing: { chord: 0.16, taper: 0.4, sweep: 0.22, wrist: 0.42 },
    beatHz: 3.2,
    stroke: 0.8,
    glide: 0.5,
    dihedral: 0.05,
    speed: 11,
    flock: { min: 4, max: 14 },
    formation: "loose",
    altitude: { min: 12, max: 45 },
    beat: { min: 30, max: 90 },
    home: "skerry",
    roost: 6,
    cycle: { min: 70, max: 150 },
    airShare: 0.55,
    dive: 0,
    dries: false,
    perKm: 1.8,
    seasons: ["spring", "summer", "autumn", "winter"],
    passes: [],
  },
  {
    id: "audouin",
    name: "Audouin's gull",
    biomes: ["karst"],
    // The rare gull, and the elegant one: a pale grey mantle, a dark red
    // bill, and a longer, narrower wing than the yellow-legged's — it
    // fishes at night out over the deep and rests in small parties on the
    // outer islets by day.
    span: 1.3,
    length: 0.5,
    neck: 0.38,
    wing: { chord: 0.14, taper: 0.34, sweep: 0.26, wrist: 0.42 },
    beatHz: 3.4,
    stroke: 0.8,
    glide: 0.5,
    dihedral: 0.04,
    speed: 12,
    flock: { min: 2, max: 7 },
    formation: "loose",
    altitude: { min: 8, max: 35 },
    beat: { min: 40, max: 110 },
    home: "skerry",
    roost: 6,
    cycle: { min: 90, max: 180 },
    airShare: 0.5,
    dive: 0,
    dries: false,
    perKm: 0.5,
    // Gone south for the winter.
    seasons: ["spring", "summer", "autumn"],
    passes: [],
  },
  {
    id: "shag",
    name: "European shag",
    biomes: ["karst"],
    // The cormorant of the rocky coast: smaller and greener than the
    // great cormorant, in lines low over the water between the islets,
    // and standing on every rock with its wings out to dry.
    span: 1.0,
    length: 0.72,
    neck: 0.44,
    wing: { chord: 0.15, taper: 0.45, sweep: 0.12, wrist: 0.5 },
    beatHz: 4,
    stroke: 0.7,
    glide: 0.05,
    dihedral: 0.02,
    speed: 14,
    flock: { min: 3, max: 9 },
    formation: "line",
    altitude: { min: 1.5, max: 6 },
    beat: { min: 60, max: 140 },
    home: "skerry",
    roost: 4,
    cycle: { min: 120, max: 240 },
    airShare: 0.3,
    dive: 0,
    dries: true,
    perKm: 1.0,
    seasons: ["spring", "summer", "autumn", "winter"],
    passes: [],
  },
  {
    id: "shearwater",
    name: "Scopoli's shearwater",
    biomes: ["karst"],
    // THE BIRD OF THE OPEN WATER HERE: a big brown-and-white shearwater
    // that shears along the swell on stiff wings, one wingtip a hand off
    // the water, in loose lines of a few — the fulmar's flight, further
    // south, and in rafts of dozens on the sea off the islets in the
    // evening waiting for the dark to go in to the colony.
    span: 1.15,
    length: 0.48,
    neck: 0.36,
    wing: { chord: 0.13, taper: 0.36, sweep: 0.22, wrist: 0.44 },
    beatHz: 3.2,
    stroke: 0.5,
    glide: 0.88,
    dihedral: 0.0,
    speed: 13,
    flock: { min: 3, max: 10 },
    formation: "loose",
    altitude: { min: 1.5, max: 10 },
    beat: { min: 70, max: 180 },
    home: "water",
    roost: 9,
    cycle: { min: 120, max: 260 },
    airShare: 0.8,
    dive: 0,
    dries: false,
    perKm: 1.0,
    sea: { offshore: { min: 120, max: 800 }, reach: 900 },
    seasons: ["spring", "summer", "autumn"],
    passes: [],
  },
  {
    id: "yelkouan",
    name: "Yelkouan shearwater",
    biomes: ["karst"],
    // The small dark shearwater of this sea, here the whole year: black
    // above and white below, in fast lines low over the water on quick
    // stiff beats between glides, and the one bird that says a rider has
    // gone properly offshore in the winter.
    span: 0.8,
    length: 0.35,
    neck: 0.36,
    wing: { chord: 0.13, taper: 0.36, sweep: 0.2, wrist: 0.44 },
    beatHz: 4.5,
    stroke: 0.55,
    glide: 0.65,
    dihedral: 0.0,
    speed: 14,
    flock: { min: 6, max: 20 },
    formation: "line",
    altitude: { min: 1, max: 6 },
    beat: { min: 60, max: 160 },
    home: "water",
    roost: 10,
    cycle: { min: 100, max: 220 },
    airShare: 0.8,
    dive: 0,
    dries: false,
    perKm: 0.9,
    sea: { offshore: { min: 130, max: 800 }, reach: 900 },
    seasons: ["spring", "summer", "autumn", "winter"],
    passes: [],
  },
  {
    id: "commontern",
    name: "Common tern",
    biomes: ["karst"],
    // The arctic tern's part on a coast the arctic tern only passes: the
    // same hover, the same fold, the same plunge over the shallows of
    // the cove, from the spring to the end of the summer.
    span: 0.8,
    length: 0.34,
    neck: 0.36,
    wing: { chord: 0.11, taper: 0.25, sweep: 0.32, wrist: 0.34 },
    beatHz: 4.2,
    stroke: 1.0,
    glide: 0.15,
    dihedral: 0.04,
    speed: 9,
    flock: { min: 3, max: 9 },
    formation: "loose",
    altitude: { min: 5, max: 16 },
    beat: { min: 25, max: 70 },
    home: "shore",
    roost: 5,
    cycle: { min: 60, max: 120 },
    airShare: 0.75,
    dive: 14,
    dries: false,
    perKm: 0.9,
    seasons: ["spring", "summer"],
    passes: [],
  },
  {
    id: "swift",
    name: "Pallid swift",
    biomes: ["karst"],
    // THE SOUND OF A SUMMER EVENING ON THIS COAST: screaming parties of
    // swifts tearing round the cliffs and over the water at the fastest
    // speed in the roster, on a scythe of a wing, and never landing —
    // a swift feeds, drinks and sleeps on the wing, and the only thing it
    // ever touches is the crack in the cliff it nests in. So its "home"
    // is the shore and its share in the air is nearly everything.
    span: 0.44,
    length: 0.17,
    neck: 0.34,
    wing: { chord: 0.12, taper: 0.2, sweep: 0.4, wrist: 0.36 },
    beatHz: 7,
    stroke: 0.8,
    glide: 0.5,
    dihedral: 0.02,
    speed: 22,
    flock: { min: 6, max: 20 },
    formation: "loose",
    altitude: { min: 15, max: 90 },
    beat: { min: 40, max: 120 },
    home: "shore",
    roost: 8,
    cycle: { min: 60, max: 140 },
    airShare: 0.92,
    dive: 0,
    dries: false,
    perKm: 1.2,
    seasons: ["spring", "summer", "autumn"],
    passes: [],
  },
  {
    id: "eleonora",
    name: "Eleonora's falcon",
    biomes: ["karst"],
    // THE RAPTOR: a slim dark falcon that nests on the sea cliffs of the
    // outer islets in the late summer, to feed its young on the small
    // birds crossing the sea in the autumn — so it hunts OUT over the
    // water, high, on a long narrow wing, and it hangs in the wind off the
    // cliff for minutes at a time. One to a stretch of coast, on a rock
    // rather than a tree: the cliff is where it lives.
    span: 1.15,
    length: 0.4,
    neck: 0.36,
    wing: { chord: 0.16, taper: 0.3, sweep: 0.34, wrist: 0.42 },
    beatHz: 3.2,
    stroke: 0.7,
    glide: 0.6,
    dihedral: 0.03,
    speed: 16,
    flock: { min: 1, max: 1 },
    formation: "loose",
    altitude: { min: 30, max: 120 },
    beat: { min: 60, max: 160 },
    home: "skerry",
    roost: 0,
    cycle: { min: 150, max: 300 },
    airShare: 0.6,
    dive: 0,
    dries: false,
    perKm: 0.3,
    seasons: ["summer", "autumn"],
    passes: [],
  },
  {
    id: "griffon",
    name: "Griffon vulture",
    biomes: ["karst"],
    // The biggest wing on any coast: a vulture that nests on the sea
    // cliffs here and nowhere else in the game, and soars over them and
    // out over the water on a plank of a wing held in a shallow V,
    // hardly beating at all, in twos and threes, hundreds of metres up.
    // A thing a rider looks UP at.
    span: 2.6,
    length: 1.05,
    neck: 0.32,
    wing: { chord: 0.27, taper: 0.8, sweep: 0.06, wrist: 0.55 },
    beatHz: 1.4,
    stroke: 0.5,
    glide: 0.95,
    dihedral: 0.12,
    speed: 13,
    flock: { min: 1, max: 4 },
    formation: "loose",
    altitude: { min: 80, max: 220 },
    beat: { min: 90, max: 200 },
    home: "shore",
    roost: 6,
    cycle: { min: 200, max: 400 },
    airShare: 0.6,
    dive: 0,
    dries: false,
    perKm: 0.2,
    seasons: ["spring", "summer", "autumn", "winter"],
    passes: [],
  },
  {
    id: "hoodedcrow",
    name: "Hooded crow",
    biomes: ["karst"],
    // The raven's part on a coast with no raven: grey and black, in pairs
    // along the shore the whole year, working the tideline and the
    // harbour and shouting at everything.
    span: 0.98,
    length: 0.48,
    neck: 0.4,
    wing: { chord: 0.2, taper: 0.5, sweep: 0.14, wrist: 0.48 },
    beatHz: 3.2,
    stroke: 0.7,
    glide: 0.3,
    dihedral: 0.03,
    speed: 12,
    flock: { min: 1, max: 3 },
    formation: "loose",
    altitude: { min: 8, max: 40 },
    beat: { min: 40, max: 110 },
    home: "shore",
    roost: 5,
    cycle: { min: 150, max: 300 },
    airShare: 0.45,
    dive: 0,
    dries: false,
    perKm: 0.6,
    seasons: ["spring", "summer", "autumn", "winter"],
    passes: [],
  },
  {
    id: "stork",
    name: "White stork",
    biomes: ["karst"],
    // The crane's part, and it goes over WITH the cranes: a big white
    // bird with black flight feathers, its neck and its legs both out, in
    // a loose vee at height — north up the coast in the spring, south
    // down it in the autumn, over the sea because this is the one place
    // the sea is narrow enough to cross. Never lives here.
    span: 2.0,
    length: 1.05,
    neck: 0.48,
    wing: { chord: 0.24, taper: 0.7, sweep: 0.08, wrist: 0.52 },
    beatHz: 1.8,
    stroke: 0.55,
    glide: 0.6,
    dihedral: 0.06,
    speed: 14,
    flock: { min: 8, max: 20 },
    formation: "vee",
    altitude: { min: 120, max: 220 },
    beat: { min: 100, max: 200 },
    roost: 0,
    cycle: { min: 200, max: 400 },
    airShare: 0,
    dive: 0,
    dries: false,
    perKm: 0,
    seasons: [],
    passage: {
      height: { min: 120, max: 220 },
      birds: { min: 8, max: 20 },
      shapes: ["vee", "loose"],
      share: 3,
    },
    passes: ["spring", "autumn"],
  },
];
