// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// GENERATED by `make coasts` (scripts/coast-preview.mjs). Do not edit.
//
// WHAT EACH COAST BANNER IS A PICTURE OF. The banners themselves are JPEGs
// under pwa/public/previews/, rendered by the real game at a staged moment
// on the shore's FIRST pinned level — so what they show depends entirely on
// that level's seed, its coast and the day it pins.
//
// Nothing at runtime reads this. It exists because a photograph cannot be
// recomputed and compared the way a course line can: without it, re-seeding
// a shore's first level leaves a banner of water nobody rides, under a sky
// the level is no longer set in, and NOTHING anywhere would say so.
// tests/shore_preview_test.ts holds this against campaign-levels.ts.

export type CoastShot = {
  /** The pinned level the moment was staged on. */
  level: string;
  seed: number;
  /** The staged moment and the rung of the camera ladder it was seen from. */
  scene: string;
  camera: string;
  hour: number;
  season: string;
  weather: string;
  /** The mean wind, m/s, and the groundswell standing off the coast, m. */
  wind: number;
  swell: number;
};

export const COAST_SHOTS: Record<string, CoastShot> = {
  mangrove: {
    level: "mangrove-1",
    seed: 5,
    scene: "cruise",
    camera: "heli",
    hour: 13,
    season: "summer",
    weather: "clear",
    wind: 7,
    swell: 1.5,
  },
  taiga: {
    level: "taiga-1",
    seed: 26,
    scene: "cruise",
    camera: "heli",
    hour: 7,
    season: "summer",
    weather: "clear",
    wind: 7,
    swell: 1.5,
  },
  arctic: {
    level: "arctic-1",
    seed: 38,
    scene: "cruise",
    camera: "heli",
    hour: 1,
    season: "summer",
    weather: "clear",
    wind: 7,
    swell: 1.5,
  },
  karst: {
    level: "karst-1",
    seed: 16,
    scene: "cruise",
    camera: "heli",
    hour: 10,
    season: "summer",
    weather: "clear",
    wind: 7,
    swell: 1.5,
  },
};
