// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// THE MODEL REGISTRY: every kind of object the game draws, and whether what
// the player sees is a MODEL made in Blender (`make models`, committed in
// `pwa/models/`, the `blender-assets` skill) or GENERATED by the game's own
// code at run time. One row an asset: its ids, where each half lives and
// the switch that sends a modelled asset back to its code.
//
// A modelled asset keeps its code builder — the switch's other side, and
// what the model is judged against — so every row names one. The water, the
// shore's ground, the sky, the sea ice, the wake, the spray and the
// footprints are surfaces and effects, not objects, and are not rows.
//
// `tests/model_registry_test.ts` holds it to the tree: the Blender rows'
// files are exactly the files the build packs (`modelFiles`), every path
// named here exists, and `docs/models.md` carries `renderModelRegistry()`
// (`make model-registry` rewrites it, and prettier pads its columns).
// DOM-free and three-free.

import { CRAFT_IDS, FAUNA_IDS } from "@engine";

import { BIRD_IDS } from "./bird-defs.ts";
import { MARK_KINDS } from "./mark-shapes.ts";
import { ROCK_KINDS } from "./rock-variants.ts";
import { TREE_KINDS } from "./tree-variants.ts";
import { UNDER_KINDS } from "./undergrowth-variants.ts";

export type ModelSource = "blender" | "code";

export type ModelRow = {
  /** What is drawn, in the player's words. */
  asset: string;
  /** Every id of it the game draws. */
  ids: readonly string[];
  /** Where the drawn geometry comes from today. */
  source: ModelSource;
  /** The code that builds it — the only builder of a `code` row, the
   * switched-off one of a `blender` row. */
  code: readonly string[];
  /** What puts it in the scene. */
  drawnBy: string;
  /** A modelled asset's Blender builder, its committed files (published
   * names under `pwa/models/`, and their shape as one pattern), and the
   * build switch that turns it back. */
  blender?: { builder: string; files: readonly string[]; pattern: string; switch: string };
  /** Anything a reader should know that the columns do not say. */
  note?: string;
};

export const MODEL_REGISTRY: readonly ModelRow[] = [
  {
    asset: "Crafts",
    ids: CRAFT_IDS,
    source: "blender",
    code: ["pwa/src/game/craft-body.ts", "pwa/src/game/craft-styles.ts"],
    drawnBy: "pwa/src/game/craft-models.ts",
    blender: {
      builder: "scripts/blender/craft.py",
      files: CRAFT_IDS.map((id) => `${id}.glb`),
      pattern: "<id>.glb",
      switch: "VITE_MODEL_CRAFTS",
    },
    note: "the ghost and the craft card draw the same models",
  },
  {
    asset: "Rider",
    ids: ["rider"],
    source: "blender",
    code: ["pwa/src/game/rider.ts", "pwa/src/game/rider-pose.ts"],
    drawnBy: "pwa/src/game/craft-models.ts",
    blender: {
      builder: "scripts/blender/rider.py",
      files: ["rider.glb"],
      pattern: "rider.glb",
      switch: "VITE_MODEL_RIDERS",
    },
    note: "one model, dressed in each grid slot's kit",
  },
  {
    asset: "Trees",
    ids: TREE_KINDS,
    source: "blender",
    code: ["pwa/src/game/flora-shapes.ts"],
    drawnBy: "pwa/src/game/flora.ts",
    blender: {
      builder: "scripts/blender/tree.py",
      files: TREE_KINDS.map((k) => `trees/${k}.glb`),
      pattern: "trees/<kind>.glb",
      switch: "VITE_MODEL_TREES",
    },
    note: "every tree-form roster row, six variants a kind, dressed in its row's colours",
  },
  {
    asset: "Undergrowth: bushes, tufts, reeds and loose stone",
    ids: UNDER_KINDS,
    source: "blender",
    code: ["pwa/src/game/flora-shapes.ts"],
    drawnBy: "pwa/src/game/flora.ts",
    blender: {
      builder: "scripts/blender/undergrowth.py",
      files: UNDER_KINDS.map((k) => `undergrowth/${k}.glb`),
      pattern: "undergrowth/<kind>.glb",
      switch: "VITE_MODEL_UNDERGROWTH",
    },
    note: "every other roster row, four variants a kind, dressed in its row's colours",
  },
  {
    asset: "Birds",
    ids: BIRD_IDS,
    source: "blender",
    code: ["pwa/src/game/bird-shapes.ts"],
    drawnBy: "pwa/src/game/birds.ts",
    blender: {
      builder: "scripts/blender/bird.py",
      files: BIRD_IDS.map((id) => `birds/${id}.glb`),
      pattern: "birds/<id>.glb",
      switch: "VITE_MODEL_BIRDS",
    },
    note: "one model a species, dressed in its style, flapped by the same shader",
  },
  {
    asset: "Sea life",
    ids: FAUNA_IDS,
    source: "blender",
    code: ["pwa/src/game/fauna.ts", "pwa/src/game/fauna-styles.ts"],
    drawnBy: "pwa/src/game/fauna.ts",
    blender: {
      builder: "scripts/blender/fauna.py",
      files: FAUNA_IDS.map((id) => `fauna/${id}.glb`),
      pattern: "fauna/<id>.glb",
      switch: "VITE_MODEL_FAUNA",
    },
    note: "one model a species, its hide painted by the code's own rule, bent by the same shader",
  },
  {
    asset: "Boulders, erratics and reefs",
    ids: ROCK_KINDS,
    source: "blender",
    code: ["pwa/src/game/rocks.ts"],
    drawnBy: "pwa/src/game/rocks.ts",
    blender: {
      builder: "scripts/blender/rock.py",
      files: ROCK_KINDS.map((k) => `rocks/${k}.glb`),
      pattern: "rocks/<kind>.glb",
      switch: "VITE_MODEL_ROCKS",
    },
    note: "four variants a kind, tinted the coast's stone per instance",
  },
  {
    asset: "Stacks, skerries and the mark",
    ids: ["skerry", "stack", "mark"],
    source: "code",
    code: ["pwa/src/game/rock-shapes.ts"],
    drawnBy: "pwa/src/game/rocks.ts",
    note: "carved for itself at its own waterline, which no shared model can carry",
  },
  {
    asset: "The course's marks: the gate mark and the rounding buoy",
    ids: MARK_KINDS,
    source: "blender",
    code: ["pwa/src/game/gates.ts", "pwa/src/game/buoys.ts"],
    drawnBy: "pwa/src/game/renderer.ts",
    blender: {
      builder: "scripts/blender/mark.py",
      files: MARK_KINDS.map((k) => `marks/${k}.glb`),
      pattern: "marks/<kind>.glb",
      switch: "VITE_MODEL_MARKS",
    },
    note: "dressed a primitive a material; the buoy scaled to its solid",
  },
  {
    asset: "The course's geometry: rings and ramps",
    ids: ["ring", "ramp"],
    source: "code",
    code: ["pwa/src/game/gates.ts"],
    drawnBy: "pwa/src/game/renderer.ts",
    note: "sized per gate and per level, so no one model fits",
  },
  {
    asset: "The edge net",
    ids: ["edge-net"],
    source: "code",
    code: ["pwa/src/game/edge-net.ts"],
    drawnBy: "pwa/src/game/edge-net.ts",
    note: "a lattice cut to each level's own tornado edge, not an object with a shape of its own",
  },
];

const cell = (s: string): string => s.replaceAll("|", "\\|");
const paths = (ps: readonly string[]): string => ps.map((p) => `\`${p}\``).join(", ");

/** The registry as the markdown table `docs/models.md` carries. */
export function renderModelRegistry(rows: readonly ModelRow[] = MODEL_REGISTRY): string {
  const head = [
    "| Asset | Source | Kinds | Blender builder | Committed models | Code builder | Drawn by | Switch |",
    "| --- | --- | --- | --- | --- | --- | --- | --- |",
  ];
  const body = rows.map((r) => {
    const b = r.blender;
    const models = b ? `${b.files.length} × \`pwa/models/${b.pattern}\`` : "—";
    return `| ${[
      r.asset + (r.note ? ` (${r.note})` : ""),
      r.source === "blender" ? "**Blender**" : "code",
      `${r.ids.length}: ${r.ids.join(", ")}`,
      b ? `\`${b.builder}\`` : "—",
      models,
      paths(r.code),
      `\`${r.drawnBy}\``,
      b ? `\`${b.switch}=0\`` : "—",
    ]
      .map(cell)
      .join(" | ")} |`;
  });
  return [...head, ...body].join("\n");
}

/** The markers the table stands between in `docs/models.md`. */
export const REGISTRY_BEGIN = "<!-- model-registry:begin (make model-registry) -->";
export const REGISTRY_END = "<!-- model-registry:end -->";

/** The table between the markers in `page`. */
export function registryTableIn(page: string): string {
  const a = page.indexOf(REGISTRY_BEGIN);
  const b = page.indexOf(REGISTRY_END);
  if (a < 0 || b < a) throw new Error("docs/models.md has lost its registry markers");
  return page.slice(a + REGISTRY_BEGIN.length, b);
}

/** Two tables that say the same thing, whatever the padding in their cells
 * (prettier aligns the page's columns; the renderer does not). */
export function sameTable(a: string, b: string): boolean {
  const norm = (t: string): string =>
    t
      .split("\n")
      .map((l) =>
        l
          .trim()
          .replace(/\s*\|\s*/g, "|")
          .replace(/-{3,}/g, "---"),
      )
      .filter(Boolean)
      .join("\n");
  return norm(a) === norm(b);
}

/** `page` with the text between the markers replaced by `table`. */
export function withRegistryTable(page: string, table: string): string {
  const a = page.indexOf(REGISTRY_BEGIN);
  const b = page.indexOf(REGISTRY_END);
  if (a < 0 || b < a) throw new Error("docs/models.md has lost its registry markers");
  return `${page.slice(0, a + REGISTRY_BEGIN.length)}\n\n${table}\n\n${page.slice(b)}`;
}
