// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// GENERATED by `make routes` (scripts/shore-routes.mjs). Do not edit.
//
// Every pinned shore's racing line, as the level card draws it: the built
// course path, simplified to within a pixel and quantised to a byte a
// coordinate. It is here as source rather than as a file to fetch because
// the whole campaign fits in a couple of kilobytes — cheaper to bundle than
// to ask the network for while a card is already on screen.
//
// Regenerate whenever the generator's rules move UNDER A LEVEL — which, now
// that a level names the generator that built it (`mapgen/versions.ts`),
// should only ever be a level being deliberately moved to a newer version.
// A stale route is a picture of water nobody rides any more.

export type ShoreRoute = {
  /** The polyline, base64 of (x, y) byte pairs. 0 is the west and north
   * edge of the line's own bounding box, 255 the east and south. */
  d: string;
  /** How much wider than tall that bounding box is, in the world — what
   * the card fits its drawing box to, so a shore keeps its shape. */
  aspect: number;
  /** THE SHORE THIS WAS DRAWN FROM. Nothing at runtime reads it; it is the
   * receipt, and `tests/shore_preview_test.ts` holds it against
   * `campaign-levels.ts`. A level's seed or swell edited without a
   * `make previews` leaves a picture of the water that USED to be there,
   * under the name of the water that is — and that is invisible unless the
   * data says which water it drew.
   *
   * `digest` is the strongest field of the five: it is `levelDigest` of
   * the shore this line came off, so it is checkable against the campaign's
   * own pin without rebuilding anything. */
  spec: {
    seed: number;
    track: string;
    tricks: boolean;
    swell: number;
    /** WHICH GENERATOR drew it (`mapgen/versions.ts`). */
    version: number;
    digest: string;
  };
};

export const SHORE_ROUTES: Record<string, ShoreRoute> = {
  "mangrove-1": {
    d: "y//E8b/gt6CpVbVP5kT1Pvw3/y79Jvkh8x3rGeMX1RbMF58gjSCEHngZcxVrC2EFSgA8ADMCBBAAUgha",
    aspect: 0.5989,
    spec: { seed: 5, track: "coast", tricks: false, swell: 1.5, version: 1, digest: "343fd408" },
  },
  "mangrove-2": {
    d: "/C//I/4e+xfyD+oJ3QTOAb8AdCIUMgs2BDwAQwBIAU0GVBJaKGAyZDlqPXE+eDqCOYc6i0WeSK9Gvj/bP+hC9Er/",
    aspect: 0.622,
    spec: { seed: 34, track: "coast", tricks: true, swell: 1.5, version: 1, digest: "ca3a8363" },
  },
  "mangrove-3": {
    d: "ePVl5lrgNtUkzBS+DLQHqwKdAZMBeAo1DiYUGR0OKgQ1AUQAxEjVU+Je7mz1d/uF/pT/pP2u+LzvzOLZ0uW69Kz7of6W/4r9efRa4DbVJ84Xwg63Ca8EogGYAI0Afgo1ECEXFSALKgQ1AUQApTfBRtJR31vraPNz+YD9j/+Z/6T8s/bB78zm1tnhs/io/Z3/kv6H+3n0a+s=",
    aspect: 1.4095,
    spec: { seed: 18, track: "circuit", tricks: false, swell: 2, version: 1, digest: "931504e7" },
  },
  "mangrove-4": {
    d: "FGsHXQBOLQNDAFkCbQqCF4oakhubG6gXrxO/B8cDzwHYAeEC7Qb0C/wT/xzobO5y83z0g/OO8pTX48v/",
    aspect: 0.8071,
    spec: { seed: 41, track: "coast", tricks: false, swell: 6, version: 1, digest: "680b58cd" },
  },
  "mangrove-5": {
    d: "///48fTrrbZleS9+HHwQdwdwAWgAYgJZBlMPTBdIJEVUP109aDdvL3IqcyRyGHYPfwiQAqMAygDUAeEF6AnxEPQW+CH9LA==",
    aspect: 0.6214,
    spec: { seed: 45, track: "coast", tricks: true, swell: 2.5, version: 1, digest: "0f3cda4f" },
  },
  "mangrove-6": {
    d: "///x8+Hpz+On15POg8RztG2wZq1arE+vSbMyxivJJMwczBHKB8UAvSZuJBcrEDoFRQFMAFQBWwN5E4EZ",
    aspect: 0.9802,
    spec: { seed: 39, track: "coast", tricks: false, swell: 9, version: 1, digest: "71dc1445" },
  },
  "taiga-1": {
    d: "AO4P7RvyVP9a+GHsZt1voHaKeoCCdZRmmlmcTp1FmiSdFKMIpwOuALYBuwS/CMQRxhv6Vv1f/2v+gPyQ96P0qu+y6LfeuQ==",
    aspect: 1.6902,
    spec: { seed: 26, track: "coast", tricks: false, swell: 1.5, version: 1, digest: "e7013a27" },
  },
  "taiga-2": {
    d: "/3r5TfMz6h7dDoAAdQdsD2UYXyJbLFg3WU5XVVVcUGNLaEBuGXUOewmABIcBjgCVAJ0CpAarDbMYuSO8K71Cuoj4lv8=",
    aspect: 0.9302,
    spec: { seed: 22, track: "coast", tricks: true, swell: 1.5, version: 1, digest: "2ae00e60" },
  },
  "taiga-3": {
    d: "G2stT2EGcAF+AIsDqA3WGuUi8iz3Mvw8/kP/Tv5Z+2Pwd+WHxaq9t6zYn+uT9of8ev9t/mD7VfYw2xLLCcMDugGzAKgBnQWSD34tT2EGbAJ1AH4AiwOoDcoW2hzlIu8p9C/6Of9H/lX7Y/J054TFqr23rNih6JP2h/x//nb/bf5k/Vj4TvEw2xLLCcMFvQK2AKsBoQOWDYIjXg==",
    aspect: 0.8089,
    spec: { seed: 10, track: "circuit", tricks: false, swell: 3, version: 1, digest: "633d011a" },
  },
  "taiga-4": {
    d: "wACzFKBOnGWNno+ilaairLOw3LXwu/fA/sf/zPzT9Nrr3uHh0OS35IDedN5i4VLlSulD7Tn2LPsV/wD+",
    aspect: 0.4,
    spec: { seed: 3, track: "coast", tricks: false, swell: 5, version: 1, digest: "c0a79382" },
  },
  "taiga-5": {
    d: "vf+473uuc6AMbgVoAmIAWwFVBE8JSRBEGUAoPUg7UTheMmQtaCdrIWsXbhF2CH4EjQGYANcG5grxEfkZ/CP8M/9H/FP4XfJm4Hc=",
    aspect: 0.6078,
    spec: { seed: 27, track: "coast", tricks: true, swell: 3, version: 1, digest: "5d0064f7" },
  },
  "taiga-6": {
    d: "CbYfxTzaxP/Q+9r24/Du5vnX/M/+x/+6/bK9W8JPyUjZO9804iziI+Ab2xPUDcUFuQKnAJoBjgSECHIVaRpdHksgPiAyHScZExAADQ==",
    aspect: 0.6594,
    spec: { seed: 14, track: "coast", tricks: false, swell: 12, version: 1, digest: "2ef01c2b" },
  },
  "arctic-1": {
    d: "/wD1EfAd13bUe/rW+ODy6+nz3vjR+sT4vPSn55/kluON5IHoeu1y9mf9Wv9N/j34K+0Z4w/bBc4BwwCzA6cJmBCPHINIYlpRYUdoPW8o",
    aspect: 0.9111,
    spec: { seed: 38, track: "coast", tricks: false, swell: 1.5, version: 1, digest: "d7e251ca" },
  },
  "arctic-2": {
    d: "/4vsp7fWrNKhyGZ/XX9Uh0+JSIZDgT50O2kxJy0VKQwlBR4AGQESBgwSCCMGMAVUEKURwg/XC+kF9wD/",
    aspect: 3.0784,
    spec: { seed: 46, track: "coast", tricks: true, swell: 2, version: 1, digest: "488334af" },
  },
  "arctic-3": {
    d: "t8ek4prujviA/Xf/af4o6hvjD9oGzQLCALYBpQeVEYEbdSZpXzfEANMF2wvmF+4l9DX6S/5i/3P8hPWU6abZs7jJsNCd6pL1ifqA/Xf/bf8x7R/mF+EP2gbNAbwAsQGlBJoLixt1KmZNSF83xADKAtcI3w/pG/Aq+ED+XP9t/X/6ivWU6abZs7jJsNCh5pbxjviF/Hz+cv9k/DHtJOgT3QnRAsIAtgCrA58Jjxh5KmZNSF83xADFANMF2wvmF+4l9jr8UP9o/nn8hPiP8pnpptmzuMmq2Q==",
    aspect: 1.2366,
    spec: { seed: 19, track: "circuit", tricks: false, swell: 4, version: 1, digest: "03e26448" },
  },
  "arctic-4": {
    d: "/1nxVuNZpIObhZCGV8dS40/tSvVD/T3/OP4z+y70Kewl3CLDJoklbyFeHVQWSgtCBTUAHgAQAQA=",
    aspect: 2.3702,
    spec: { seed: 2, track: "coast", tricks: false, swell: 1.5, version: 1, digest: "56b98d31" },
  },
  "arctic-5": {
    d: "/wDuB+QO10XdXt+U2p7RpcjezOXM6cnwxfS4+6z+n/+S/of6ffVn3mHbV9ZL0z7TMdUh2RjZC9gA0w==",
    aspect: 0.5391,
    spec: { seed: 45, track: "coast", tricks: true, swell: 6, version: 1, digest: "deefc154" },
  },
  "arctic-6": {
    d: "6an7hf8w+SbwGuUQ2wrKA7oApwGYBIsLgRF2G2ktYzJYNlA3RTUxKyYoGikTKw0vBzQCPgBFAVAEVwhdDWIVZzG+O8xK3V3vcf8=",
    aspect: 0.9551,
    spec: { seed: 41, track: "coast", tricks: false, swell: 18, version: 1, digest: "ab837aaa" },
  },
  "karst-1": {
    d: "mwCYDJkVukvAV8Jgw23Be76Kt5n+xf/M/NP02e7d3uHM4rHem+GQ5Yrpf/Z1+2T/Tv4a9Q/wBekA3wLHBcAQrw==",
    aspect: 0.5373,
    spec: { seed: 16, track: "coast", tricks: false, swell: 1.5, version: 1, digest: "e7fe3c64" },
  },
  "karst-2": {
    d: "wv++77bjqNWJun2rdp9yj2yGYX9Tekh4J3cddRNyCGsDZQBbAVUETwlJEUQZQCk9PzxOOp8AsgHjB/EM+RH/XfVp",
    aspect: 0.5907,
    spec: { seed: 27, track: "coast", tricks: true, swell: 1.5, version: 1, digest: "e5cf8437" },
  },
  "karst-3": {
    d: "RrwfpRObDJMEhQF7AHACYRkgIhMpCzgDSQBUAV8Dcwx8Ed5f6233f/6S/53/p/q29cDrzL3ztPmp/Z7/k/6C+nDuYN9MxUW9PLcfpRObCY4EhQF7AHACYRMvHBwiEykLOANJAFQBXwNpB3gP3l/ucfmD/I3/mP+n/LH4u/LE59DG7Lj2qf2e/5P+iPx993TxZONJwUG6MrE=",
    aspect: 0.917,
    spec: { seed: 12, track: "circuit", tricks: false, swell: 3, version: 1, digest: "15ea7ccc" },
  },
  "karst-4": {
    d: "wQDTEeMj8Dj5S/+o9sDr0d3gz+jE7Lzus+6n7ZTmf9l312vWX9pY3lLjQvU7+jP9J/8f/hf8EPcL8xuTGYwVhQl6BHMCawBf",
    aspect: 0.9784,
    spec: { seed: 24, track: "coast", tricks: false, swell: 5, version: 1, digest: "eaefa45b" },
  },
  "karst-5": {
    d: "/13oXKFFjkWEQ34+UgBMAkYFPww8EjoZOh89OjpHNE8vUxxZF1wSYQd2AYwAmgCnBsUL2BLoGPQg/w==",
    aspect: 1.0374,
    spec: { seed: 15, track: "coast", tricks: true, swell: 4, version: 1, digest: "b6a2c1b2" },
  },
  "karst-6": {
    d: "AWABSDMFQgFVAGMDcQh+D4sblCabMqA/plOqWbJhuGTDZ91k6GbuafRt+3X/f/+J+5P3mfKe66LSp8aulfOL9XP9X/8=",
    aspect: 0.9462,
    spec: { seed: 47, track: "coast", tricks: false, swell: 9, version: 1, digest: "8eff5d03" },
  },
};
