#!/usr/bin/env node
// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// THE LEVEL BOXES' LAYOUTS — every pinned shore's racing line, as the shape
// the level card draws in its box, built ahead of time and committed as
// data.
//
// The measurement that decided this: DRAWING a line is free and BUILDING one
// is not. Stroking a shore at thumbnail size costs under a millisecond;
// `generateLevel` costs one to two SECONDS for the same shore here — a
// coast, a course, the rocks, two baked grids and an analysis, and again for
// every sub-seed the analyzer rejected — and twelve of them is most of half
// a minute. A card that built its own pictures would open, freeze, and fill
// in long after the player had pressed something.
//
// So only the expensive half happens here. What ships is a POLYLINE rather
// than a picture — a few hundred bytes a shore, into
// pwa/src/game/shore-routes.ts — and the card strokes it as an SVG path.
// That way the line is sharp at any size and takes the colour of the box it
// sits in, instead of being a picture of one state of one box.
//
// The banner behind a SHORE is a different problem and a different tool: a
// shore is six levels, so it gets a real render of the coast rather than a
// map of any one of them (scripts/coast-preview.mjs).
//
//   make routes
//
// The encoding itself is `pwa/src/game/shore-preview.ts`'s, beside the
// decoding it is the inverse of and shared with tests/shore_preview_test.ts:
// this is generator output, so it goes stale the moment the rules move, and
// that test rebuilds a pinned shore and checks the committed bytes against
// it.
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import process from "node:process";

import { parseArgs } from "./lib/cli.mjs";
import { aliasEngine } from "./lib/engine-alias.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
aliasEngine(root);
const { levelDigest } = await import(join(root, "engine/index.ts"));
const { SHORES } = await import(join(root, "pwa/src/game/campaign-levels.ts"));
const { buildCampaignLevel } = await import(join(root, "pwa/src/game/campaign.ts"));
// The encoder is the card's OWN, read off the module that also decodes it
// (`shore-preview.ts`) — a second implementation here would be a tool writing
// bytes the card cannot read back, which is the one failure the format's two
// halves are stated together to prevent. §23.6: tooling imports the app, and
// nothing imports tooling, so this is the direction the arrow already runs.
const { routeOf } = await import(join(root, "pwa/src/game/shore-preview.ts"));

const args = parseArgs(
  process.argv.slice(2),
  {
    out: {
      kind: "string",
      default: "pwa/src/game/shore-routes.ts",
      help: "where the module lands",
    },
  },
  "usage: node scripts/shore-routes.mjs [--out path]",
);

/** The generated module, written the way prettier would have written it so
 * that re-running this tool on a clean tree is a no-op.
 *
 * One field per line rather than an entry per line, which looks wasteful and
 * is not a choice: a route's base64 runs to several hundred characters, so
 * every entry is past the print width and prettier breaks all of them. An
 * emitter that writes the tidier one-liner just means `make fmt` rewrites
 * this file every time it is generated, and `make fmt-check` fails on any
 * branch that regenerated it without formatting afterwards. */
function routesModule(rows) {
  const entries = rows
    .map(
      ({ id, route, spec }) =>
        `  "${id}": {\n    d: "${route.d}",\n    aspect: ${route.aspect},\n` +
        `    spec: { seed: ${spec.seed}, track: "${spec.track}", tricks: ${spec.tricks},` +
        ` swell: ${spec.swell}, version: ${spec.version}, digest: "${spec.digest}" },\n  },`,
    )
    .join("\n");
  return `// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// GENERATED by \`make routes\` (scripts/shore-routes.mjs). Do not edit.
//
// Every pinned shore's racing line, as the level card draws it: the built
// course path, simplified to within a pixel and quantised to a byte a
// coordinate. It is here as source rather than as a file to fetch because
// the whole campaign fits in a couple of kilobytes — cheaper to bundle than
// to ask the network for while a card is already on screen.
//
// Regenerate whenever the generator's rules move UNDER A LEVEL — which, now
// that a level names the generator that built it (\`mapgen/versions.ts\`),
// should only ever be a level being deliberately moved to a newer version.
// A stale route is a picture of water nobody rides any more.

export type ShoreRoute = {
  /** The polyline, base64 of (x, y) byte pairs. 0 is the west and north
   * edge of the line's own bounding box, 255 the east and south. */
  d: string;
  /** How much wider than tall that bounding box is, in the world — what
   * the card fits its drawing box to, so a shore keeps its shape. */
  aspect: number;
  /** THE SHORE THIS WAS DRAWN FROM. Nothing at runtime reads it; it is the
   * receipt, and \`tests/shore_preview_test.ts\` holds it against
   * \`campaign-levels.ts\`. A level's seed or swell edited without a
   * \`make previews\` leaves a picture of the water that USED to be there,
   * under the name of the water that is — and that is invisible unless the
   * data says which water it drew.
   *
   * \`digest\` is the strongest field of the five: it is \`levelDigest\` of
   * the shore this line came off, so it is checkable against the campaign's
   * own pin without rebuilding anything. */
  spec: {
    seed: number;
    track: string;
    tricks: boolean;
    swell: number;
    /** WHICH GENERATOR drew it (\`mapgen/versions.ts\`). */
    version: number;
    digest: string;
  };
};

export const SHORE_ROUTES: Record<string, ShoreRoute> = {
${entries}
};
`;
}

const routes = [];
/** Shores whose build no longer matches the digest the campaign pins. Not
 * this tool's to fix — see the report at the foot. */
const stale = [];
for (const shore of SHORES) {
  for (const pinned of shore.levels) {
    const started = Date.now();
    // The level's OWN build, through the campaign's own function: a box
    // that draws water the player never rides is worse than no box at all.
    const level = buildCampaignLevel(pinned);
    const route = routeOf(level);
    const digest = levelDigest(level);
    if (digest !== pinned.digest) stale.push(pinned.id);
    routes.push({
      id: pinned.id,
      route,
      spec: {
        seed: pinned.seed,
        track: pinned.track,
        tricks: pinned.mode === "tricks",
        swell: pinned.swell,
        version: pinned.version,
        digest,
      },
    });
    console.log(
      `  ${pinned.id.padEnd(12)} gen v${pinned.version}  ` +
        `${(level.course.length / 1000).toFixed(2).padStart(5)} km  ` +
        `${String(route.points).padStart(4)} points  ` +
        `${String(route.d.length).padStart(4)} B  ` +
        `${digest}${digest === pinned.digest ? "" : ` != pinned ${pinned.digest} !!`}` +
        `  (${Date.now() - started} ms)`,
    );
  }
}

writeFileSync(join(root, args.out), routesModule(routes));
const bytes = routes.reduce((sum, r) => sum + r.route.d.length, 0);
console.log(`\n${args.out} — ${routes.length} routes, ${(bytes / 1024).toFixed(1)} KB of polyline`);
if (stale.length > 0) {
  // Not this tool's to fix: a shore that no longer builds to its pinned
  // digest is the campaign's problem (`campaign` skill), and the routes
  // written above are of the water that builds TODAY. Said loudly and
  // exited non-zero so it cannot be the line nobody read.
  console.error(
    `\n!! ${stale.length} shore(s) no longer build to the digest campaign-levels.ts pins:\n` +
      `   ${stale.join(", ")}\n` +
      `   The routes above are of the water that builds today. Settle the digest first.`,
  );
  process.exit(1);
}
